#!/usr/bin/env python3

__license__ = """
 File: pyharm-movie
 
 BSD 3-Clause License
 
 Copyright (c) 2020-2023, Ben Prather and AFD Group at UIUC
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 
 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 
 3. Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived from
    this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""


import os, sys
import click
import glob
import inspect
import itertools
import multiprocessing
import psutil
import shutil
import subprocess
import textwrap
import time
import tqdm
import warnings

import numpy as np
import pandas
# Make sure we use Agg
import matplotlib
matplotlib.use('Agg')

import pyharm
from pyharm.plots.frame import frame
from pyharm.parallel import calc_nthreads

# Use mpi4py if available, or multiprocessing
try:
    import mpi4py
    from mpi4py import MPI
    from mpi4py.futures import MPICommExecutor, MPIPoolExecutor
    if MPI.COMM_WORLD.Get_rank() == 0:
        print("MPI Available", file=sys.stderr)
    # Use MPI if we've gone and loaded it, process binding sucks
    use_mpi = True
    def do_out():
        return MPI.COMM_WORLD.Get_rank() == 0
except ImportError:
    use_mpi = False
    def do_out():
        return True

# This extends the help message to print valid movies
class ExtensibleCmd(click.Command):
    def format_help(self, ctx, formatter):
        click.Command.format_help(self, ctx, formatter)

        figure_list = inspect.getmembers(pyharm.plots.figures, \
                predicate=lambda f: inspect.isfunction(f) and f.__module__ == pyharm.plots.figures.__name__)

        formatter.write("\nValid movies:\n")
        for fnname, fn in figure_list:
            if fnname[0] != "_":
                formatter.write("  "+fnname+":\n")
                if pyharm.plots.figures.__dict__[fnname].__doc__ is not None:
                    # Take out all whitespace from the docstring
                    docstring = textwrap.shorten(pyharm.plots.figures.__dict__[fnname].__doc__, 1e6).replace("\n"," ")
                    # Reflow and indent
                    formatter.write(textwrap.indent(textwrap.fill(docstring), "    ") + "\n\n")
        formatter.write("\n...or any valid key consisting of a variable and any operations.\n")

def out_path(run_path, kwargs):
    if 'PYHARM_DUMPS_DIR' in os.environ:
        base_path = os.path.realpath(os.environ['PYHARM_DUMPS_DIR'])
    else:
        base_path = os.path.realpath(os.getcwd())
    if 'PYHARM_OUTPUT_DIR' in os.environ and kwargs['output_dir'] == ".":
        out_base_path = os.path.realpath(os.environ['PYHARM_OUTPUT_DIR'])
    else:
        out_base_path = os.path.realpath(kwargs['output_dir'])

    return run_path.replace(base_path, out_base_path)

def frame_print(fname, kwargs):
    # TODO surely we can tweak this to update tqdm instead!
    tstart, tend = float(kwargs['tstart']), float(kwargs['tend'])
    tdump = pyharm.io.get_dump_time(fname)
    if (tstart is not None and tdump < tstart) or \
        (tend is not None and tdump > tend):
        return
    print("Imaging t={}".format(int(tdump)), file=sys.stderr)
    frame(fname, kwargs)

@click.command(cls=ExtensibleCmd)
@click.argument('movie_types', nargs=1) # does click support list args?
@click.argument('paths', nargs=-1, type=click.Path(exists=True))
# Common options
@click.option('-s', '--tstart', default=None, help="Start time.")
@click.option('-e', '--tend', default=None, help="End time.")
@click.option('-n', '--nthreads', default=None, help="Number of processes to use, if not using MPI")
@click.option('-o', '--output-dir', default=".", help="Base directory for outputs. Any folder structure of models will be preserved.")
@click.option('--multizone', is_flag=True, help="Image a multizone run.  Call on each run folder separately!")
@click.option('--nodiag', is_flag=True, help="Don't load a history/diagnostic text file")
@click.option('--amr-level', default=0, help="AMR level to interpolate KHARMA file with mesh refinement")
@click.option('--encode', is_flag=True, help="Encode the movie with ffmpeg in x264, with reasonable defaults")
@click.option('--encode-options', default="-vcodec libx264 -crf 15 -pix_fmt yuv420p", help="Encoding options for ffmpeg calls")
# Figure options
@click.option('--fig-x', default=16.0, help="Figure width in inches.")
@click.option('--fig-y', default=9.0, help="Figure height in inches.")
@click.option('--fig-dpi', default=100, help="DPI of resulting figure.")
@click.option('--left', default=0.07, help="Left side padding of figure (as in subplots_adjust).")
@click.option('--right', default=0.93, help="Right side padding of figure (as in subplots_adjust).")
@click.option('--bottom', default=None, help="Bottom padding of figure (as in subplots_adjust).")
@click.option('--top', default=None, help="Top padding of figure (as in subplots_adjust).")
@click.option('--wspace', default=None, help="Width spacing between plots in figure (as in subplots_adjust).")
@click.option('--hspace', default=None, help="Height spacing between plots in figure (as in subplots_adjust).")
@click.option('--no-title', is_flag=True, help="Omit a plot title e.g. of simulation time.")
# Dump file plotting options
@click.option('-g','--ghost_zones', is_flag=True, help="Plot ghost zones.")
@click.option('-at','--at','--at-zone', 'at', default=0, help="Phi zone to plot at.")
@click.option('-av','--av','--average', 'average', is_flag=True, help="Average quantities over phi.")
@click.option('--sum', is_flag=True, help="Sum quantities over phi.")
@click.option('-sh','--sh','--shading', 'shading', default='flat', help="Shading: flat, nearest, gouraud.")
@click.option('--vmin', default=None, help="Colorscale minimum.")
@click.option('--vmax', default=None, help="Colorscale maximum.")
@click.option('--cmap', default='jet', help="Colormap.")
@click.option('--log', is_flag=True, help="Plot natural log of the specified variable. Colorbar is properly marked vs prepending log_")
@click.option('-sz','--sz','--size', 'size', default=None, help="Window size, in M each side of central object.")
@click.option('--xmin', default=None, help="Window X minimum.")
@click.option('--xmax', default=None, help="Window X maximum.")
@click.option('--ymin', default=None, help="Window Y minimum.")
@click.option('--ymax', default=None, help="Window Y maximum.")
@click.option('--log-r', is_flag=True, help="Make the plots logarithmic in radius.")
@click.option('--overlay-field', is_flag=True, help="Overlay field lines.")
@click.option('--nlines', default=20, help="Number of total field lines to overlay.")
@click.option('--overlay-grid', is_flag=True, help="Overlay simulation zone borders.")
@click.option('--overlay-grid-spacing', default=1, help="Only plot grid every X lines.")
@click.option('--overlay-blocks', is_flag=True, help="Overlay simulation block borders.")
@click.option('--array', is_flag=True, help="Plot values in array space: Cartesian, without coordinate transformations.")
@click.option('--bh/--no-bh', default=True, help="Whether to show the BH shadow.")
@click.option('--no-grid-cache', is_flag=True, help="Don't cache geometry.  For plotting large Cartesian simulations.")
@click.option('--prefer-iharm3d', is_flag=True, help="Prefer iharm3d-format files if available alongside KHARMA output")
# Extras
@click.option('--tag', default="", help="String to append to the movie name")
@click.option('--accurate-fnames', is_flag=True, help="Name frames by 1/100M, for close spaced outputs.")
@click.option('--numeric-fnames', is_flag=True, help="Name frames by file number.")
@click.option('-r', '--resume', is_flag=True, help="Continue a previous run, by skipping existing frames")
@click.option('-d', '--debug', is_flag=True, help="Serial operation for debugging")
@click.option('--nompi', is_flag=True, help="Avoid MPI even if available")
@click.version_option(package_name='pyharm')
def movie(movie_types, paths, **kwargs):
    """Generate movies of type MOVIE_TYPE from dumps at each of PATHS.

    "Movies" are generated as collections of frames in .png format, named frame_tXXXXXXXX.png by simulation time in M,
    and placed in a subdirectory "frames_MOVIE_TYPE" of the given PATH.  One can easily generate a single .mp4 movie
    from these using ffmpeg or similar, see 'scripts/batch/' for examples.

    Each PATH can contain dump files in any format readable by pyharm, either in the given directory or a subdirectory
    named "dumps", "dumps_kharma" or similar.

    MOVIE_TYPE can be any variable known to pyharm (see README, variables.py) or any "figure" function in figures.py, listed below.
    A common first movie is 'log_rho', for example, which will plot phi=0 toroidal and midplane poloidal slices of the log base 10
    of the density. You can create mutiple movies using a comma-separated list without spaces, e.g. 'log_rho,traditional'.

    If run within an MPI job/allocation with mpi4py installed, movie.py will attempt to use all allocated nodes to generate
    frames.  YMMV wildly with MPI installations, with mpi4py installed via pip generally a better choice than through conda.
    """

    # Enumerate runs we want to image, by absolute path
    path_dirs = [os.path.realpath(p) for p in paths if os.path.isdir(p)]
    if len(path_dirs) == 0:
        # We passed single file arguments only.  We use this signal to treat them as one movie.
        path_dirs = [None]
    # Total movies: types * runs
    movie_types = movie_types.split(",")
    if do_out(): print("Generating ",len(path_dirs)*len(movie_types)," movie(s)", file=sys.stderr)

    # For each run...
    # TODO we read files repeatedly for different movies here.
    #      If running multiple movies with exactly the same options becomes common (?),
    #      this could be made a lot faster by returning to running them together.
    #      Really, we need a movie/analysis spec to do everything in one run...
    for run_path, movie_type in itertools.product(path_dirs, movie_types):
        if run_path is None:
            # We passed in a bunch of files and want one movie
            files = [os.path.realpath(p) for p in paths]
            run_path = os.path.dirname(files[0])
        else:
            # Try to load known filenames from this path, skip if there are none
            try:
                files = pyharm.io.get_fnames(run_path, prefer_iharm3d=kwargs['prefer_iharm3d'])
            except FileNotFoundError:
                continue

        # Timestamp formatting: appropriate left padding...
        if kwargs['tend'] is None:
            kwargs['time_digits'] = int(np.log10(pyharm.io.get_dump_time(files[-1])+1))+1
        else:
            kwargs['time_digits'] = int(np.log10(float(kwargs['tend'])))+1
        # ...and automatically make times accurate to hundredths if t_end < 100
        if kwargs['time_digits'] < 3:
            kwargs['accurate_fnames'] = True
        
        # Add these so we can pass on just the kwargs object to worker function
        # We pass filenames themselves, so `frame` doesn't care about run_path
        kwargs['movie_types'] = movie_type
        if kwargs['encode']:
            kwargs['out_path'] = "/tmp" # TODO allow changing
            kwargs['encode_path'] = out_path(run_path, kwargs)
        else:
            kwargs['out_path'] = out_path(run_path, kwargs)

        # Reading from base_path + run_name. Output to out_path + run_name + frames_X
        movie_name = movie_type+("_"+kwargs['tag'] if kwargs['tag'] != "" else "")
        frame_dir = os.path.join(kwargs['out_path'], "frames_"+movie_name)
        # Unless we're resuming a previous video, just kill the directory
        if do_out():
            if not kwargs['resume'] and os.path.exists(frame_dir):
                shutil.rmtree(frame_dir)
            os.makedirs(frame_dir, exist_ok=True)

        # Option to avoid loading diag file since not everything needs it
        # TODO mark whether given movies even require diag
        kwargs['diag'] = None
        if not kwargs['nodiag']:
            diag_names = ("eht_out.h5", "*.h5", "*.hst", "*/*.hst")
            for base_path,diag_name in itertools.product((out_path(run_path, kwargs), run_path), diag_names):
                if len(glob.glob(os.path.join(base_path, diag_name))) > 0:
                    fname = glob.glob(os.path.join(base_path, diag_name))[0]
                    if do_out(): print("Trying to load diagnostics from {}".format(fname), file=sys.stderr)
                    try:
                        # This works for either reduction results (.h5) or KHARMA's history file (.hst)
                        pyharm.load_results(fname)
                        # Record only the name, the AnaResults object is not pickle-able
                        kwargs['diag'] = fname
                        break
                    except (IOError, pandas.errors.ParserError) as e:
                        print(e, file=sys.stderr)
                        continue

        if do_out():
            print("Imaging outputs in {} with movie {}".format(run_path, movie_type), file=sys.stderr)
            print("Outputting to {}".format(frame_dir), file=sys.stderr)
        # Serial operation for debugging/memory analysis
        if 'debug' in kwargs and kwargs['debug']:
            # Import profiling only if used, start it
            import cProfile, pstats, io
            from pstats import SortKey
            from pympler import tracker
            pr = cProfile.Profile()
            pr.enable()
            # Run sequentially to make profiling & backtraces work
            for fname in files:
                tr = tracker.SummaryTracker()
                frame(fname, kwargs)
                tr.print_diff()

            pr.disable()
            s = io.StringIO()
            ps = pstats.Stats(pr, stream=s).sort_stats(SortKey.TIME)
            ps.print_stats(10)
            print(s.getvalue())

        else:
            # Parallel with mpi or multiprocessing
            # Suppress math warnings for e.g. log(-)
            if not sys.warnoptions:
                warnings.simplefilter("ignore")
            # Try to guess how many processes before we MemoryError out
            if 'nthreads' not in kwargs or kwargs['nthreads'] is None:
                if 'memory_limit' in kwargs and kwargs['memory_limit'] is not None:
                    hdr = pyharm.io.read_hdr(files[0])
                    nthreads = min(calc_nthreads(hdr, pad=0.6),
                                psutil.cpu_count())
                else:
                    nthreads = psutil.cpu_count()
            else:
                nthreads = int(kwargs['nthreads'])

            # Only use as many processes at files
            nthreads = min(nthreads, len(files))

            # This application is entirely side-effects (frame creation)
            # So we map & ignore result
            if use_mpi and not kwargs['nompi']:
                print("Using MPI")
                # Everything is set by MPI.  We inherit a situation and use it
                with MPICommExecutor() as executor:
                    if executor is not None:
                        comm_size = MPI.COMM_WORLD.Get_size()
                        print("Imaging {} files across pool size {}".format(len(files), comm_size), file=sys.stderr)
                        executor.map(frame_print, files, (kwargs,)*len(files))
            else:
                print("Using {} processes".format(nthreads))
                with multiprocessing.Pool(nthreads) as pool:
                    args = zip(files, (kwargs,)*len(files))
                    pool.starmap_async(frame, tqdm.tqdm(args, total=len(files))).get(720000)

        if do_out() and kwargs['encode']:
            movie_path = os.path.join(kwargs['encode_path'], movie_name+".mp4")
            print(f"Encoding to {movie_path}")
            framerate = 8 if len(files) < 300 else 24
            call = f"ffmpeg -f image2 -i {os.path.join(frame_dir, "%*.png")} -r {framerate} {kwargs['encode_options']} -y {movie_path}"
            subprocess.run(call, shell=True, check=True)
            # Remove from /tmp, it's often not cleaned after jobs
            shutil.rmtree(frame_dir)

        if do_out(): print("Imaged model {} with movie(s) {}".format(run_path, movie_types), file=sys.stderr)

if __name__ == "__main__":
    movie()
