#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

if [[ $1 == "prompt" || $1 == "shell" || $1 == "terminal" || $1 == "session" ]]; then
  exec python -m pyharm ${@:2}
elif [[ $1 == "ana" ]]; then
  exec ${SCRIPT_DIR}/pyharm-analysis ${@:2}
elif [[ $1 == "-h" || $1 == "--help" ]]; then
  echo "Available sub-commands:"
  echo
  for fil in $(find $SCRIPT_DIR -name pyharm-* -printf "%f\n"); do
    echo "${fil:7}"
  done
  echo "prompt"
  echo
  echo "type pyharm <command> --help for information on each command"
  echo
else
  exec ${SCRIPT_DIR}/pyharm-${1} ${@:2}
fi
